/**
 * Computes the data for the Emergency Vet Access report and writes it to
 * src/data/emergency-vet-report.ts as a typed TS module. Run when the
 * underlying provider data changes.
 *
 * Usage: npx tsx --env-file=.env.local scripts/build-emergency-vet-report.ts
 */
import { createClient } from '@supabase/supabase-js'
import { writeFileSync } from 'fs'
import { resolve } from 'path'

type Row = { state: string; city: string; category: string; rating: number | null; review_count: number | null; slug: string }

async function main() {
  const sb = createClient(process.env.SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!, { auth: { persistSession: false } })

  let all: Row[] = []
  let off = 0
  while (true) {
    const { data, error } = await sb
      .from('providers')
      .select('state, city, category, rating, review_count, slug')
      .range(off, off + 999)
    if (error) throw error
    if (!data?.length) break
    all = all.concat(data as Row[])
    if (data.length < 1000) break
    off += 1000
  }

  const em = all.filter(r => r.category === 'emergency_vets')

  // group by city
  const byCity = new Map<string, { city: string; state: string; count: number; providers: Row[] }>()
  for (const r of em) {
    const k = `${r.city}|${r.state}`
    const cur = byCity.get(k) || { city: r.city, state: r.state, count: 0, providers: [] }
    cur.count += 1
    cur.providers.push(r)
    byCity.set(k, cur)
  }
  const cityRows = [...byCity.values()].sort((a, b) => a.count - b.count)

  const deserts = cityRows.filter(c => c.count === 1)
  const scarce = cityRows.filter(c => c.count === 2)
  const saturated = cityRows.filter(c => c.count >= 10).sort((a, b) => b.count - a.count).slice(0, 15)

  // state-level averages
  const stateBuckets = new Map<string, number[]>()
  for (const c of cityRows) {
    const arr = stateBuckets.get(c.state) || []
    arr.push(c.count)
    stateBuckets.set(c.state, arr)
  }
  const stateSummary = [...stateBuckets.entries()]
    .map(([state, arr]) => ({
      state,
      cities: arr.length,
      avgEmergencyVets: arr.reduce((s, n) => s + n, 0) / arr.length,
      totalEmergencyVets: arr.reduce((s, n) => s + n, 0),
    }))
    .sort((a, b) => a.avgEmergencyVets - b.avgEmergencyVets)

  const totalProviders = all.length
  const totalEmergency = em.length
  const totalCities = byCity.size
  const citiesWithOnlyOne = deserts.length
  const citiesWithTwoOrFewer = deserts.length + scarce.length

  const report = {
    generatedAt: new Date().toISOString().slice(0, 10),
    totals: {
      totalProviders,
      totalEmergencyVets: totalEmergency,
      totalCitiesAnalyzed: totalCities,
      citiesWithOnlyOne,
      citiesWithTwoOrFewer,
      pctCitiesUnderThree: +(citiesWithTwoOrFewer / totalCities * 100).toFixed(1),
    },
    deserts: deserts.map(c => ({
      city: c.city,
      state: c.state,
      emergencyVetCount: c.count,
      provider: {
        name: c.providers[0].slug.split('-').slice(-4).join(' '),
        slug: c.providers[0].slug,
      },
    })),
    scarce: scarce.map(c => ({ city: c.city, state: c.state, emergencyVetCount: c.count })),
    bestCovered: saturated.map(c => ({ city: c.city, state: c.state, emergencyVetCount: c.count })),
    stateSummary: stateSummary.slice(0, 15).concat(stateSummary.slice(-5)).map(s => ({
      state: s.state,
      cities: s.cities,
      avgEmergencyVets: +s.avgEmergencyVets.toFixed(1),
      totalEmergencyVets: s.totalEmergencyVets,
    })),
  }

  const out = `// AUTO-GENERATED by scripts/build-emergency-vet-report.ts — do not edit by hand
export interface VetDesertCity { city: string; state: string; emergencyVetCount: number; provider: { name: string; slug: string } }
export interface ScarceCity { city: string; state: string; emergencyVetCount: number }
export interface BestCoveredCity { city: string; state: string; emergencyVetCount: number }
export interface StateSummary { state: string; cities: number; avgEmergencyVets: number; totalEmergencyVets: number }

export const emergencyVetReport = ${JSON.stringify(report, null, 2)} as const
`
  writeFileSync(resolve(process.cwd(), 'src/data/emergency-vet-report.ts'), out, 'utf-8')
  console.log(`✓ Wrote src/data/emergency-vet-report.ts`)
  console.log(`  ${citiesWithOnlyOne} cities with 1 emergency vet`)
  console.log(`  ${scarce.length} cities with 2`)
  console.log(`  ${totalEmergency} total emergency vets across ${totalCities} cities`)
}

main().catch(e => { console.error(e); process.exit(1) })
