// AUTO-GENERATED by scripts/build-emergency-vet-report.ts — do not edit by hand
export interface VetDesertCity { city: string; state: string; emergencyVetCount: number; provider: { name: string; slug: string } }
export interface ScarceCity { city: string; state: string; emergencyVetCount: number }
export interface BestCoveredCity { city: string; state: string; emergencyVetCount: number }
export interface StateSummary { state: string; cities: number; avgEmergencyVets: number; totalEmergencyVets: number }

export const emergencyVetReport = {
  "generatedAt": "2026-04-18",
  "totals": {
    "totalProviders": 9442,
    "totalEmergencyVets": 863,
    "totalCitiesAnalyzed": 82,
    "citiesWithOnlyOne": 8,
    "citiesWithTwoOrFewer": 15,
    "pctCitiesUnderThree": 18.3
  },
  "deserts": [
    {
      "city": "Clearwater",
      "state": "FL",
      "emergencyVetCount": 1,
      "provider": {
        "name": "aa animal er center",
        "slug": "fl-clearwater-emergencyvets-aa-animal-er-center"
      }
    },
    {
      "city": "Savannah",
      "state": "GA",
      "emergencyVetCount": 1,
      "provider": {
        "name": "emergencyvets st john veterinarian",
        "slug": "ga-savannah-emergencyvets-st-john-veterinarian"
      }
    },
    {
      "city": "Cleveland",
      "state": "OH",
      "emergencyVetCount": 1,
      "provider": {
        "name": "great lakes veterinary specialists",
        "slug": "oh-cleveland-emergencyvets-vca-great-lakes-veterinary-specialists"
      }
    },
    {
      "city": "St. Paul",
      "state": "MN",
      "emergencyVetCount": 1,
      "provider": {
        "name": "emergencyvets bluepearl pet hospital",
        "slug": "mn-st-paul-emergencyvets-bluepearl-pet-hospital"
      }
    },
    {
      "city": "Overland Park",
      "state": "KS",
      "emergencyVetCount": 1,
      "provider": {
        "name": "wilson eric r dvm",
        "slug": "ks-overland-park-emergencyvets-mission-med-vet-wilson-eric-r-dvm"
      }
    },
    {
      "city": "Richmond",
      "state": "VA",
      "emergencyVetCount": 1,
      "provider": {
        "name": "veterinary emergency special center",
        "slug": "va-richmond-emergencyvets-dogwood-veterinary-emergency-special-center"
      }
    },
    {
      "city": "Missoula",
      "state": "MT",
      "emergencyVetCount": 1,
      "provider": {
        "name": "veterinary specialists and emergency",
        "slug": "mt-missoula-emergencyvets-sentinel-veterinary-specialists-and-emergency"
      }
    },
    {
      "city": "Lexington",
      "state": "KY",
      "emergencyVetCount": 1,
      "provider": {
        "name": "advanced animal care emergency",
        "slug": "ky-lexington-emergencyvets-advanced-animal-care-emergency"
      }
    }
  ],
  "scarce": [
    {
      "city": "Las Vegas",
      "state": "NV",
      "emergencyVetCount": 2
    },
    {
      "city": "Pittsburgh",
      "state": "PA",
      "emergencyVetCount": 2
    },
    {
      "city": "Indianapolis",
      "state": "IN",
      "emergencyVetCount": 2
    },
    {
      "city": "Jackson",
      "state": "MS",
      "emergencyVetCount": 2
    },
    {
      "city": "New Orleans",
      "state": "LA",
      "emergencyVetCount": 2
    },
    {
      "city": "Stamford",
      "state": "CT",
      "emergencyVetCount": 2
    },
    {
      "city": "Grand Rapids",
      "state": "MI",
      "emergencyVetCount": 2
    }
  ],
  "bestCovered": [
    {
      "city": "Queens",
      "state": "NY",
      "emergencyVetCount": 22
    },
    {
      "city": "Mesa",
      "state": "AZ",
      "emergencyVetCount": 21
    },
    {
      "city": "El Paso",
      "state": "TX",
      "emergencyVetCount": 21
    },
    {
      "city": "Houston",
      "state": "TX",
      "emergencyVetCount": 20
    },
    {
      "city": "Jersey City",
      "state": "NJ",
      "emergencyVetCount": 20
    },
    {
      "city": "Sacramento",
      "state": "CA",
      "emergencyVetCount": 20
    },
    {
      "city": "Fayetteville",
      "state": "AR",
      "emergencyVetCount": 20
    },
    {
      "city": "Manhattan",
      "state": "NY",
      "emergencyVetCount": 20
    },
    {
      "city": "Staten Island",
      "state": "NY",
      "emergencyVetCount": 20
    },
    {
      "city": "Washington",
      "state": "DC",
      "emergencyVetCount": 20
    },
    {
      "city": "Sarasota",
      "state": "FL",
      "emergencyVetCount": 19
    },
    {
      "city": "Fort Worth",
      "state": "TX",
      "emergencyVetCount": 19
    },
    {
      "city": "Atlanta",
      "state": "GA",
      "emergencyVetCount": 19
    },
    {
      "city": "Colorado Springs",
      "state": "CO",
      "emergencyVetCount": 19
    },
    {
      "city": "Baltimore",
      "state": "MD",
      "emergencyVetCount": 19
    }
  ],
  "stateSummary": [
    {
      "state": "KS",
      "cities": 1,
      "avgEmergencyVets": 1,
      "totalEmergencyVets": 1
    },
    {
      "state": "MT",
      "cities": 1,
      "avgEmergencyVets": 1,
      "totalEmergencyVets": 1
    },
    {
      "state": "NV",
      "cities": 1,
      "avgEmergencyVets": 2,
      "totalEmergencyVets": 2
    },
    {
      "state": "IN",
      "cities": 1,
      "avgEmergencyVets": 2,
      "totalEmergencyVets": 2
    },
    {
      "state": "MS",
      "cities": 1,
      "avgEmergencyVets": 2,
      "totalEmergencyVets": 2
    },
    {
      "state": "LA",
      "cities": 2,
      "avgEmergencyVets": 2.5,
      "totalEmergencyVets": 5
    },
    {
      "state": "MN",
      "cities": 2,
      "avgEmergencyVets": 4,
      "totalEmergencyVets": 8
    },
    {
      "state": "NC",
      "cities": 2,
      "avgEmergencyVets": 4,
      "totalEmergencyVets": 8
    },
    {
      "state": "OK",
      "cities": 1,
      "avgEmergencyVets": 4,
      "totalEmergencyVets": 4
    },
    {
      "state": "DE",
      "cities": 1,
      "avgEmergencyVets": 4,
      "totalEmergencyVets": 4
    },
    {
      "state": "OH",
      "cities": 2,
      "avgEmergencyVets": 5,
      "totalEmergencyVets": 10
    },
    {
      "state": "ID",
      "cities": 1,
      "avgEmergencyVets": 5,
      "totalEmergencyVets": 5
    },
    {
      "state": "CT",
      "cities": 2,
      "avgEmergencyVets": 5.5,
      "totalEmergencyVets": 11
    },
    {
      "state": "ME",
      "cities": 1,
      "avgEmergencyVets": 7,
      "totalEmergencyVets": 7
    },
    {
      "state": "FL",
      "cities": 8,
      "avgEmergencyVets": 7.6,
      "totalEmergencyVets": 61
    },
    {
      "state": "AR",
      "cities": 2,
      "avgEmergencyVets": 17.5,
      "totalEmergencyVets": 35
    },
    {
      "state": "WI",
      "cities": 1,
      "avgEmergencyVets": 18,
      "totalEmergencyVets": 18
    },
    {
      "state": "CA",
      "cities": 5,
      "avgEmergencyVets": 18.6,
      "totalEmergencyVets": 93
    },
    {
      "state": "MD",
      "cities": 1,
      "avgEmergencyVets": 19,
      "totalEmergencyVets": 19
    },
    {
      "state": "DC",
      "cities": 1,
      "avgEmergencyVets": 20,
      "totalEmergencyVets": 20
    }
  ]
} as const
