// AUTO-GENERATED by scripts/build-availability-report.ts — do not edit
export interface StateRanking {
  state: string
  stateName: string
  totalProviders: number
  population: number
  per100k: number
  vet: number
  emergency: number
  groomers: number
}

export const availabilityReport = {
  "generatedAt": "2026-04-18",
  "totals": {
    "totalProviders": 9442,
    "statesAnalyzed": 45,
    "nationalAvgPer100k": 2.91
  },
  "mostSaturated": [
    {
      "state": "DC",
      "stateName": "District of Columbia",
      "totalProviders": 140,
      "population": 678972,
      "per100k": 20.62,
      "vet": 24,
      "emergency": 20,
      "groomers": 23
    },
    {
      "state": "MT",
      "stateName": "Montana",
      "totalProviders": 150,
      "population": 1132812,
      "per100k": 13.24,
      "vet": 18,
      "emergency": 1,
      "groomers": 28
    },
    {
      "state": "AK",
      "stateName": "Alaska",
      "totalProviders": 96,
      "population": 733406,
      "per100k": 13.09,
      "vet": 7,
      "emergency": 16,
      "groomers": 16
    },
    {
      "state": "NE",
      "stateName": "Nebraska",
      "totalProviders": 206,
      "population": 1978379,
      "per100k": 10.41,
      "vet": 32,
      "emergency": 20,
      "groomers": 34
    },
    {
      "state": "DE",
      "stateName": "Delaware",
      "totalProviders": 94,
      "population": 1031890,
      "per100k": 9.11,
      "vet": 15,
      "emergency": 4,
      "groomers": 17
    },
    {
      "state": "ME",
      "stateName": "Maine",
      "totalProviders": 92,
      "population": 1395722,
      "per100k": 6.59,
      "vet": 11,
      "emergency": 7,
      "groomers": 16
    },
    {
      "state": "AR",
      "stateName": "Arkansas",
      "totalProviders": 195,
      "population": 3067732,
      "per100k": 6.36,
      "vet": 19,
      "emergency": 35,
      "groomers": 32
    },
    {
      "state": "IA",
      "stateName": "Iowa",
      "totalProviders": 199,
      "population": 3207004,
      "per100k": 6.21,
      "vet": 26,
      "emergency": 17,
      "groomers": 39
    },
    {
      "state": "HI",
      "stateName": "Hawaii",
      "totalProviders": 88,
      "population": 1435138,
      "per100k": 6.13,
      "vet": 18,
      "emergency": 0,
      "groomers": 19
    },
    {
      "state": "KS",
      "stateName": "Kansas",
      "totalProviders": 179,
      "population": 2940546,
      "per100k": 6.09,
      "vet": 21,
      "emergency": 1,
      "groomers": 36
    }
  ],
  "leastCovered": [
    {
      "state": "WA",
      "stateName": "Washington",
      "totalProviders": 111,
      "population": 7812880,
      "per100k": 1.42,
      "vet": 11,
      "emergency": 12,
      "groomers": 18
    },
    {
      "state": "CA",
      "stateName": "California",
      "totalProviders": 574,
      "population": 38965193,
      "per100k": 1.47,
      "vet": 62,
      "emergency": 93,
      "groomers": 101
    },
    {
      "state": "NJ",
      "stateName": "New Jersey",
      "totalProviders": 140,
      "population": 9290841,
      "per100k": 1.51,
      "vet": 35,
      "emergency": 24,
      "groomers": 33
    },
    {
      "state": "PA",
      "stateName": "Pennsylvania",
      "totalProviders": 205,
      "population": 12961683,
      "per100k": 1.58,
      "vet": 27,
      "emergency": 17,
      "groomers": 35
    },
    {
      "state": "IL",
      "stateName": "Illinois",
      "totalProviders": 217,
      "population": 12549689,
      "per100k": 1.73,
      "vet": 24,
      "emergency": 16,
      "groomers": 38
    },
    {
      "state": "OH",
      "stateName": "Ohio",
      "totalProviders": 205,
      "population": 11785935,
      "per100k": 1.74,
      "vet": 22,
      "emergency": 10,
      "groomers": 38
    },
    {
      "state": "WI",
      "stateName": "Wisconsin",
      "totalProviders": 110,
      "population": 5910955,
      "per100k": 1.86,
      "vet": 15,
      "emergency": 18,
      "groomers": 18
    },
    {
      "state": "MI",
      "stateName": "Michigan",
      "totalProviders": 205,
      "population": 10037261,
      "per100k": 2.04,
      "vet": 26,
      "emergency": 19,
      "groomers": 37
    },
    {
      "state": "VA",
      "stateName": "Virginia",
      "totalProviders": 193,
      "population": 8715698,
      "per100k": 2.21,
      "vet": 19,
      "emergency": 19,
      "groomers": 39
    },
    {
      "state": "OK",
      "stateName": "Oklahoma",
      "totalProviders": 90,
      "population": 4053824,
      "per100k": 2.22,
      "vet": 9,
      "emergency": 4,
      "groomers": 20
    }
  ],
  "allStates": [
    {
      "state": "DC",
      "stateName": "District of Columbia",
      "totalProviders": 140,
      "population": 678972,
      "per100k": 20.62,
      "vet": 24,
      "emergency": 20,
      "groomers": 23
    },
    {
      "state": "MT",
      "stateName": "Montana",
      "totalProviders": 150,
      "population": 1132812,
      "per100k": 13.24,
      "vet": 18,
      "emergency": 1,
      "groomers": 28
    },
    {
      "state": "AK",
      "stateName": "Alaska",
      "totalProviders": 96,
      "population": 733406,
      "per100k": 13.09,
      "vet": 7,
      "emergency": 16,
      "groomers": 16
    },
    {
      "state": "NE",
      "stateName": "Nebraska",
      "totalProviders": 206,
      "population": 1978379,
      "per100k": 10.41,
      "vet": 32,
      "emergency": 20,
      "groomers": 34
    },
    {
      "state": "DE",
      "stateName": "Delaware",
      "totalProviders": 94,
      "population": 1031890,
      "per100k": 9.11,
      "vet": 15,
      "emergency": 4,
      "groomers": 17
    },
    {
      "state": "ME",
      "stateName": "Maine",
      "totalProviders": 92,
      "population": 1395722,
      "per100k": 6.59,
      "vet": 11,
      "emergency": 7,
      "groomers": 16
    },
    {
      "state": "AR",
      "stateName": "Arkansas",
      "totalProviders": 195,
      "population": 3067732,
      "per100k": 6.36,
      "vet": 19,
      "emergency": 35,
      "groomers": 32
    },
    {
      "state": "IA",
      "stateName": "Iowa",
      "totalProviders": 199,
      "population": 3207004,
      "per100k": 6.21,
      "vet": 26,
      "emergency": 17,
      "groomers": 39
    },
    {
      "state": "HI",
      "stateName": "Hawaii",
      "totalProviders": 88,
      "population": 1435138,
      "per100k": 6.13,
      "vet": 18,
      "emergency": 0,
      "groomers": 19
    },
    {
      "state": "KS",
      "stateName": "Kansas",
      "totalProviders": 179,
      "population": 2940546,
      "per100k": 6.09,
      "vet": 21,
      "emergency": 1,
      "groomers": 36
    },
    {
      "state": "AZ",
      "stateName": "Arizona",
      "totalProviders": 436,
      "population": 7431344,
      "per100k": 5.87,
      "vet": 52,
      "emergency": 56,
      "groomers": 80
    },
    {
      "state": "NH",
      "stateName": "New Hampshire",
      "totalProviders": 79,
      "population": 1402054,
      "per100k": 5.63,
      "vet": 12,
      "emergency": 0,
      "groomers": 17
    },
    {
      "state": "NV",
      "stateName": "Nevada",
      "totalProviders": 178,
      "population": 3194176,
      "per100k": 5.57,
      "vet": 25,
      "emergency": 2,
      "groomers": 38
    },
    {
      "state": "CT",
      "stateName": "Connecticut",
      "totalProviders": 167,
      "population": 3617176,
      "per100k": 4.62,
      "vet": 19,
      "emergency": 11,
      "groomers": 31
    },
    {
      "state": "ID",
      "stateName": "Idaho",
      "totalProviders": 88,
      "population": 1964726,
      "per100k": 4.48,
      "vet": 9,
      "emergency": 5,
      "groomers": 20
    },
    {
      "state": "KY",
      "stateName": "Kentucky",
      "totalProviders": 195,
      "population": 4526154,
      "per100k": 4.31,
      "vet": 31,
      "emergency": 16,
      "groomers": 37
    },
    {
      "state": "AL",
      "stateName": "Alabama",
      "totalProviders": 192,
      "population": 5108468,
      "per100k": 3.76,
      "vet": 24,
      "emergency": 15,
      "groomers": 33
    },
    {
      "state": "FL",
      "stateName": "Florida",
      "totalProviders": 843,
      "population": 22610726,
      "per100k": 3.73,
      "vet": 120,
      "emergency": 61,
      "groomers": 168
    },
    {
      "state": "CO",
      "stateName": "Colorado",
      "totalProviders": 219,
      "population": 5877610,
      "per100k": 3.73,
      "vet": 22,
      "emergency": 26,
      "groomers": 40
    },
    {
      "state": "LA",
      "stateName": "Louisiana",
      "totalProviders": 170,
      "population": 4573749,
      "per100k": 3.72,
      "vet": 23,
      "emergency": 5,
      "groomers": 31
    },
    {
      "state": "NY",
      "stateName": "New York",
      "totalProviders": 690,
      "population": 19571216,
      "per100k": 3.53,
      "vet": 103,
      "emergency": 78,
      "groomers": 127
    },
    {
      "state": "MO",
      "stateName": "Missouri",
      "totalProviders": 195,
      "population": 6196156,
      "per100k": 3.15,
      "vet": 26,
      "emergency": 20,
      "groomers": 37
    },
    {
      "state": "MN",
      "stateName": "Minnesota",
      "totalProviders": 174,
      "population": 5737915,
      "per100k": 3.03,
      "vet": 24,
      "emergency": 8,
      "groomers": 36
    },
    {
      "state": "MD",
      "stateName": "Maryland",
      "totalProviders": 185,
      "population": 6180253,
      "per100k": 2.99,
      "vet": 20,
      "emergency": 19,
      "groomers": 26
    },
    {
      "state": "MS",
      "stateName": "Mississippi",
      "totalProviders": 88,
      "population": 2939690,
      "per100k": 2.99,
      "vet": 12,
      "emergency": 2,
      "groomers": 19
    },
    {
      "state": "UT",
      "stateName": "Utah",
      "totalProviders": 96,
      "population": 3417734,
      "per100k": 2.81,
      "vet": 14,
      "emergency": 0,
      "groomers": 20
    },
    {
      "state": "NM",
      "stateName": "New Mexico",
      "totalProviders": 59,
      "population": 2114371,
      "per100k": 2.79,
      "vet": 0,
      "emergency": 0,
      "groomers": 0
    },
    {
      "state": "IN",
      "stateName": "Indiana",
      "totalProviders": 187,
      "population": 6862199,
      "per100k": 2.73,
      "vet": 21,
      "emergency": 2,
      "groomers": 40
    },
    {
      "state": "MA",
      "stateName": "Massachusetts",
      "totalProviders": 191,
      "population": 7001399,
      "per100k": 2.73,
      "vet": 19,
      "emergency": 22,
      "groomers": 30
    },
    {
      "state": "TN",
      "stateName": "Tennessee",
      "totalProviders": 192,
      "population": 7126489,
      "per100k": 2.69,
      "vet": 23,
      "emergency": 20,
      "groomers": 37
    },
    {
      "state": "OR",
      "stateName": "Oregon",
      "totalProviders": 110,
      "population": 4233358,
      "per100k": 2.6,
      "vet": 14,
      "emergency": 10,
      "groomers": 19
    },
    {
      "state": "ND",
      "stateName": "North Dakota",
      "totalProviders": 20,
      "population": 783926,
      "per100k": 2.55,
      "vet": 0,
      "emergency": 0,
      "groomers": 0
    },
    {
      "state": "GA",
      "stateName": "Georgia",
      "totalProviders": 273,
      "population": 11029227,
      "per100k": 2.48,
      "vet": 35,
      "emergency": 20,
      "groomers": 54
    },
    {
      "state": "TX",
      "stateName": "Texas",
      "totalProviders": 684,
      "population": 30503301,
      "per100k": 2.24,
      "vet": 97,
      "emergency": 104,
      "groomers": 129
    },
    {
      "state": "NC",
      "stateName": "North Carolina",
      "totalProviders": 242,
      "population": 10835491,
      "per100k": 2.23,
      "vet": 40,
      "emergency": 8,
      "groomers": 56
    },
    {
      "state": "OK",
      "stateName": "Oklahoma",
      "totalProviders": 90,
      "population": 4053824,
      "per100k": 2.22,
      "vet": 9,
      "emergency": 4,
      "groomers": 20
    },
    {
      "state": "VA",
      "stateName": "Virginia",
      "totalProviders": 193,
      "population": 8715698,
      "per100k": 2.21,
      "vet": 19,
      "emergency": 19,
      "groomers": 39
    },
    {
      "state": "MI",
      "stateName": "Michigan",
      "totalProviders": 205,
      "population": 10037261,
      "per100k": 2.04,
      "vet": 26,
      "emergency": 19,
      "groomers": 37
    },
    {
      "state": "WI",
      "stateName": "Wisconsin",
      "totalProviders": 110,
      "population": 5910955,
      "per100k": 1.86,
      "vet": 15,
      "emergency": 18,
      "groomers": 18
    },
    {
      "state": "OH",
      "stateName": "Ohio",
      "totalProviders": 205,
      "population": 11785935,
      "per100k": 1.74,
      "vet": 22,
      "emergency": 10,
      "groomers": 38
    },
    {
      "state": "IL",
      "stateName": "Illinois",
      "totalProviders": 217,
      "population": 12549689,
      "per100k": 1.73,
      "vet": 24,
      "emergency": 16,
      "groomers": 38
    },
    {
      "state": "PA",
      "stateName": "Pennsylvania",
      "totalProviders": 205,
      "population": 12961683,
      "per100k": 1.58,
      "vet": 27,
      "emergency": 17,
      "groomers": 35
    },
    {
      "state": "NJ",
      "stateName": "New Jersey",
      "totalProviders": 140,
      "population": 9290841,
      "per100k": 1.51,
      "vet": 35,
      "emergency": 24,
      "groomers": 33
    },
    {
      "state": "CA",
      "stateName": "California",
      "totalProviders": 574,
      "population": 38965193,
      "per100k": 1.47,
      "vet": 62,
      "emergency": 93,
      "groomers": 101
    },
    {
      "state": "WA",
      "stateName": "Washington",
      "totalProviders": 111,
      "population": 7812880,
      "per100k": 1.42,
      "vet": 11,
      "emergency": 12,
      "groomers": 18
    }
  ]
} as const
